services:
  app:
    build:
      context: .
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - psql

  psql:
    image: postgres
    restart: unless-stopped
    volumes:
      - "/var/lib/postgresql/data"
    env_file: .env
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_DATABASE

volumes:
  psql:
